# docker-compose.yml
web:
  image: nginx:1.10.2-alpine
  volumes:
   - /home/ubt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
   - /home/ubt/docker/nginx/src:/usr/share/nginx/html
  ports:
   - "8080:80"
