version: '2.1'

services:
  app:
    mem_limit: 300m
    memswap_limit: 1g
    build: ./app
    environment:
      NODE_ENV: production
    volumes:
      - ./app/dist:/home/node_app/app/dist
    ports:
     - 3000:3000
